package com.example.definitelynotrobots;

/**
 * An item to be used in the grocery list
 */
public class GroceryItem extends BaseFoodItem {
    /**
     * An item to be used in the grocery list.
     * @param userID The user ID of the owner.
     * @param name The name of the item.
     * @param amount The amount of the item.
     * @param amountType The unit of measurement for the amount.
     * @param foodType The type of food the item falls under.
     * @param notes Any notes the user may need.
     */
    public GroceryItem(Integer userID, String name, Double amount, String amountType, FoodTypesEnum foodType, String notes) {
        setUserID(userID);
        setName(name);
        setAmount(amount);
        setAmountType(amountType);
        setFoodType(foodType);
        setNotes(notes);
    }
    /**
     * An item to be used in the grocery list.
     * @param id The UID of the item generated by the SQL database.
     * @param userID The user ID of the owner.
     * @param name The name of the item.
     * @param amount The amount of the item.
     * @param amountType The unit of measurement for the amount.
     * @param foodType The type of food the item falls under.
     * @param notes Any notes the user may need.
     */
    public GroceryItem(Integer id, Integer userID, String name, Double amount, String amountType, FoodTypesEnum foodType, String notes) {
        setID(id);
        setUserID(userID);
        setName(name);
        setAmount(amount);
        setAmountType(amountType);
        setFoodType(foodType);
        setNotes(notes);
    }

    @Override
    public String toString() {
        return "GroceryItem{" +
                "ID=" + getID() +
                ", UserID=" + getUserID() +
                ", Name='" + getName() + '\'' +
                ", Amount=" + getAmount() +
                ", AmountType='" + getAmountType() + '\'' +
                ", FoodType='" + getFoodType() + '\'' +
                ", Notes='" + getNotes() + '\'' +
                '}';
    }
}
